services:
  meteohost-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meteohost-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiKey=test-api-key
      - ExpressProperties__bot=50882e44-06fe-5b27-81d6-61d0216a4199:9c3c71681df5aa45c69eee2483c3329d
    restart: unless-stopped
    networks:
      - meteohost-network

networks:
  meteohost-network:
    driver: bridge